name: jetts_fitness_app
description: A Jetts Fitness app clone with login functionality.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/