// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNunSMoO4FW3kXpDKA--SpLE9M79sX2c',
    appId: '1:347712965984:web:441f011d3d46bc796ca205',
    messagingSenderId: '347712965984',
    projectId: 'jett-55c54',
    authDomain: 'jett-55c54.firebaseapp.com',
    storageBucket: 'jett-55c54.firebasestorage.app',
    measurementId: 'G-D1Q22KF8T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTNdSzuRPO4OJeJ33BOuqadlROmrXSnA',
    appId: '1:347712965984:android:798cc9c307aa18e26ca205',
    messagingSenderId: '347712965984',
    projectId: 'jett-55c54',
    storageBucket: 'jett-55c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj_hUUlEgPm_b32_wDUYRvsg9QHoewG0',
    appId: '1:347712965984:ios:2477ca593f87e05c6ca205',
    messagingSenderId: '347712965984',
    projectId: 'jett-55c54',
    storageBucket: 'jett-55c54.firebasestorage.app',
    iosBundleId: 'com.example.jett',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaj_hUUlEgPm_b32_wDUYRvsg9QHoewG0',
    appId: '1:347712965984:ios:2477ca593f87e05c6ca205',
    messagingSenderId: '347712965984',
    projectId: 'jett-55c54',
    storageBucket: 'jett-55c54.firebasestorage.app',
    iosBundleId: 'com.example.jett',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsNunSMoO4FW3kXpDKA--SpLE9M79sX2c',
    appId: '1:347712965984:web:5bd4fc0f2c9387816ca205',
    messagingSenderId: '347712965984',
    projectId: 'jett-55c54',
    authDomain: 'jett-55c54.firebaseapp.com',
    storageBucket: 'jett-55c54.firebasestorage.app',
    measurementId: 'G-CR07GPD1HC',
  );

}